table 'Swatch Products'
	lineageTag: c3a8196e-00fd-49df-b1cf-ee2a374bd20a

	measure 'Average Price' = ```
			AVERAGE([New Price]) 
			```
		lineageTag: d89088a6-9319-416b-9a5c-19825114a9cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Sales Rank' = AVERAGE([Sales Rank])
		lineageTag: 482826b5-bf53-4d4c-ae0b-69ee3058eb2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Time
		dataType: dateTime
		formatString: General Date
		lineageTag: 78e15754-bd1e-4225-8bd8-028bde364fb8
		summarizeBy: none
		sourceColumn: Time

		variation Variation
			isDefault
			relationship: fa3394d8-d106-43e9-b11b-d06df722c57e
			defaultHierarchy: LocalDateTable_58410e3f-3357-4951-92c6-65e209d7f2fd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Sales Rank'
		dataType: int64
		formatString: 0
		lineageTag: d1a060f0-7ae4-4ea0-8458-dbef1ded6fa0
		summarizeBy: sum
		sourceColumn: Sales Rank

		annotation SummarizationSetBy = Automatic

	column 'New Price'
		dataType: double
		lineageTag: d9ad92a4-d174-4c37-a013-f18878a4493b
		summarizeBy: sum
		sourceColumn: New Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'List Price'
		dataType: int64
		formatString: 0
		lineageTag: 37177102-de94-4f5a-bcce-34e121bb4e24
		summarizeBy: sum
		sourceColumn: List Price

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 32b3378a-f57e-42c7-94c3-f597c59fb99f
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Price Performance' = DIVIDE([Sales Rank], [New Price]) --Lower = better value for rank per dollar
		lineageTag: 6f38e676-fcee-435f-950b-7f1b8c71ac7f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rank Group' = IF([Sales Rank] <= 100000, "High Seller", IF([Sales Rank] <= 500000, "Medium Seller", "Low Seller"))
		lineageTag: d7385259-beea-4f09-a9fb-142422ab7f9a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Swatch Products' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Pink Watch Data", #"Blue Watch Data", #"Green Watch Data"})
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

